server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: place-service
          uri: "lb://place-service:8086"
          predicates:
            - Path=/place/**
        - id: route-service
          uri: lb://ROUTE-SERVICE
          predicates:
            - Path=/route/**
        - id: feedback-service
          uri: lb://FEEDBACK-SERVICE
          predicates:
            - Path=/feedback/**
        - id: favorites-service
          uri: lb://FAVORITES-SERVICE
          predicates:
            - Path=/favorites/**
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**
            - Path=/auth/v3/api-docs
            - Method=GET
        - id: admin-dashboard-service
          uri: lb://ADMIN-DASHBOARD-SERVICE
          predicates:
            - Path=/admin/**
      discovery:
        locator:
          enabled: true
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

jwt:
  secret:
    sign: ${JWT_SECRET:0LHQvtC20LUg0L/QvtC80L7Qs9C4INC90LDQvCDQt9Cw0LrRgNGL0YLRjCDRjdGC0L7RgiDQv9GA0LXQtNC80LXRgg==}