spring:
  application:
    name: api-gateway
  config:
    import: 'configserver:http://${CLOUD_CONFIG_HOST:localhost}:8888'

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - url: /auth/v3/api-docs
        name: Auth Service
      - url: /favorites/v3/api-docs
        name: Favorites Service
      - url: /feedback/v3/api-docs
        name: Feedback Service
      - url: /place/v3/api-docs
        name: Place Service
      - url: /route/v3/api-docs
        name: Route Service