spring:
  application:
    name: api-gateway
  config:
    import: 'configserver:http://${CLOUD_CONFIG_HOST:localhost}:8888'

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - url: /api/v1/place/v3/api-docs
        name: Auth Service